# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ain < Formula
  desc "Ain is a terminal API client. It's an alternative to postman, paw or insomnia."
  homepage "https://github.com/jonaslu/ain"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jonaslu/ain/releases/download/v1.2.0/ain_1.2.0_mac_os_arm64.tar.gz"
      sha256 "ceda7668264220c344d2f5ccbd3525114b23661e1c9bbe21fe2181b56f4b616b"

      def install
        bin.install "ain"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jonaslu/ain/releases/download/v1.2.0/ain_1.2.0_mac_os_x86_64.tar.gz"
      sha256 "a968ae17725b702a46aec16cc7feb521d806aa8421c91c71b1d9d1a456a8cda9"

      def install
        bin.install "ain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonaslu/ain/releases/download/v1.2.0/ain_1.2.0_linux_arm64.tar.gz"
      sha256 "c53d2a22a88276f6f54cb7952a23ec8e5e77193f345fe9797233fd60484b5702"

      def install
        bin.install "ain"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jonaslu/ain/releases/download/v1.2.0/ain_1.2.0_linux_x86_64.tar.gz"
      sha256 "66844173d8202ee50f32d166a99051debf0b8ac99cab9c3a704f1a7497547ad7"

      def install
        bin.install "ain"
      end
    end
  end
end
