# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ain < Formula
  desc "Ain is a terminal API client. It's an alternative to postman, paw or insomnia."
  homepage "https://github.com/jonaslu/ain"
  version "v1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonaslu/ain/releases/download/v1.4.0/ain_v1.4.0_mac_os_x86_64.tar.gz"
      sha256 "12b87b6d1c670fde181a9e3791785fe3dcd39885dd19628b0eef09d425f06da4"

      def install
        bin.install "ain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonaslu/ain/releases/download/v1.4.0/ain_v1.4.0_mac_os_arm64.tar.gz"
      sha256 "a86a1eeaaecf0aba92ba24727e48deed2e631902f9479c0d26fc788321848aa0"

      def install
        bin.install "ain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonaslu/ain/releases/download/v1.4.0/ain_v1.4.0_linux_arm64.tar.gz"
      sha256 "38eb1fa8dadde943f8092fbccba97ae93fdbdb7adca23a1ea490fcf4760cf0a5"

      def install
        bin.install "ain"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jonaslu/ain/releases/download/v1.4.0/ain_v1.4.0_linux_x86_64.tar.gz"
      sha256 "d54b875d738112488cc8678bc7d50752d4e3d8367e9d734445d6c86c8aa3a30c"

      def install
        bin.install "ain"
      end
    end
  end
end
